services:
  - type: web
    name: telegram-ai-bot
    env: python
    buildCommand: ""
    startCommand: python main.py
    envVars:
      - key: TOKEN
        value: 7429016817:AAF0dXmeSXozvNmeRJQtac8gmJcW0nMz7a4
      - key: OPENAI_API_KEY
        value: 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
